package main

import (
    "encoding/json"
    "fmt"
    "readruntime"
)

type AutoGenerated struct {
    Age   int    `json:"age"`
    Name  string `json:"name"`
    Child []int  `json:"child"`
}

func main() {
    jsonStr1 := `{"age": 14,"name": "potter", "child":[1,2,3]}`
    a := AutoGenerated{
        Child: []int{0, 10, 11},
    }
    json.Unmarshal([]byte(jsonStr1), &a)
    aa := a.Child
    debug(aa)
    fmt.Println(aa)
    fmt.Printf("%p,%p\n", a.Child, aa)
    jsonStr2 := `{"age": 12,"name": "potter", "child":[3,4,5,7,8,9, 10, 11, 20]}`
    json.Unmarshal([]byte(jsonStr2), &a)
    debug(aa)
    fmt.Println(aa, cap(aa), len(aa))
    fmt.Printf("%p,%p\n", a.Child, aa)
    runtime.KeepAlive()
}

func debug(d []int){
    fmt.Println(d)
}
